# Generated by Django 5.0.4 on 2024-10-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadedimage_detected_objects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='detected_objects',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
