# Generated by Django 5.0.4 on 2024-10-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadedimage_processing_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='processed_image',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='processing_time',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image_mobilenet',
            field=models.ImageField(blank=True, null=True, upload_to='images/processed/'),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='processed_image_yolo',
            field=models.ImageField(blank=True, null=True, upload_to='images/processed/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
