# Generated by Django 5.0.4 on 2024-10-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_uploadedimage_processed_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='processing_time_mobilenet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='processing_time_yolo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='processed_image_mobilenet',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='processed_image_yolo',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
